# CI/CD configuration for Pupper using GitLab's CI/CD Pipeline.

# Base Docker image for builds.
image: stevegrunwell/laravel-ci-pipeline

# Additional services to make available.
services:
  - postgres:9.2

# Environment variables.
variables:
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_DATABASE: pupper_test
  DB_USERNAME: postgres
  DB_PASSWORD: ""

# Define the "build" step of the pipeline
#
# These jobs get the necessary components in place to start testing the application.
Install Composer dependencies:
    stage: build
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress
        - composer prepare-env
    artifacts:
        paths:
            - .env
            - vendor
    cache:
        key: ${CI_COMMIT_REF_SLUG}-composer
        paths:
            - vendor

Install npm dependencies:
    stage: build
    script:
        - npm install --no-progress
        - npm run prod
    artifacts:
        paths:
            - public
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm
        paths:
            - node_modules

# Begin the "Test" stage of the pipeline.
#
# This is where we'll run tests, checks, and other tools to verify that the app behaves the way we
# expect it to.
PHPUnit:
    stage: test
    script:
        - phpdbg -qrr -d memory_limit=-1 vendor/bin/phpunit --testdox --coverage-text --colors=always
    artifacts:
        paths:
            - storage/logs

Jest:
    stage: test
    script:
        - npm run test-all

Check coding standards:
    stage: test
    script:
        - composer coding-standards
        - npm run lint
    cache:
        key: ${CI_COMMIT_REF_SLUG}-php-cs-fixer
        paths:
            - .php_cs.cache

Static code analysis:
    stage: test
    script:
        - php artisan code:analyse --no-progress

# Finally, define our deployment targets.
#
# Deployment logic for each environment is defined in bin/deploy.sh.
#
# All merges to "staging" will push out to the staging server (e.g. Continuous Deployment), whereas
# deployments to production must be triggered manually (e.g. Continuous Delivery).
Deploy to Staging:
    stage: deploy
    environment:
        name: Staging
        url: https://staging.pupper.stevegrunwell.com
    script:
        - bash bin/deploy.sh staging
    only:
        - staging

Deploy to Production:
    stage: deploy
    environment:
        name: Production
        url: https://pupper.stevegrunwell.com
    script:
        - bash bin/deploy.sh production
    only:
        - master
    when: manual
